SELECT
    'January' AS Month,
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-01-01'))) AS Days
UNION ALL SELECT
    'February',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-02-01')))
UNION ALL SELECT
    'March',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-03-01')))
UNION ALL SELECT
    'April',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-04-01')))
UNION ALL SELECT
    'May',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-05-01')))
UNION ALL SELECT
    'June',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-06-01')))
UNION ALL SELECT
    'July',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-07-01')))
UNION ALL SELECT
    'August',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-08-01')))
UNION ALL SELECT
    'September',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-09-01')))
UNION ALL SELECT
    'October',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-10-01')))
UNION ALL SELECT
    'November',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-11-01')))
UNION ALL SELECT
    'December',
    DAY(LAST_DAY(CONCAT(YEAR(CURDATE()), '-12-01'));
